# Proyecto de Machine Learning No Supervisado

Este proyecto estudia técnicas de aprendizaje no supervisado mediante dos datasets con características diferentes:

1. **Dataset de setas:** contiene variables categóricas y una etiqueta que indica si una seta es comestible o venenosa.
2. **Dataset de tarjetas de crédito:** contiene variables numéricas y no dispone de una etiqueta de referencia.

El proyecto se desarrollará en dos notebooks. En cada uno realizaremos:

- análisis exploratorio de datos;
- limpieza y preprocesado;
- reducción de dimensionalidad;
- aplicación de diferentes algoritmos de clustering;
- evaluación e interpretación de los grupos obtenidos;
- detección de observaciones anómalas.

## Parte 1: Dataset de setas

En este notebook analizaremos características categóricas de diferentes setas.

La variable `class` indica si una seta es:

- `e`: comestible (*edible*);
- `p`: venenosa (*poisonous*).

Aunque disponemos de esta etiqueta, **no la utilizaremos para entrenar los algoritmos de clustering**. La reservaremos para evaluar posteriormente si los grupos descubiertos sin supervisión se parecen a las clases reales.

El objetivo no es únicamente ejecutar algoritmos, sino comprender cómo influyen el tipo de datos, el preprocesado y la métrica de distancia en los resultados.

In [1]:
%pip install pandas numpy seaborn matplotlib
%pip install --upgrade pip

Requirement already satisfied: pandas in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (2.5.1)
Requirement already satisfied: seaborn in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (3.11.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pip in C:\Users\Coder\Factoria\project-unsupervised-ml\.venv\Lib\site-packages (26.2.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

sns.set_theme(style="whitegrid")
RANDOM_STATE = 42

In [3]:
data_path = "data/mushrooms.csv"

mushrooms = pd.read_csv(data_path)

mushrooms.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
from pathlib import Path

print("Carpeta actual:", Path.cwd())
print("Existe el CSV:", Path("data/mushrooms.csv").exists())

Carpeta actual: C:\Users\Coder\Factoria\project-unsupervised-ml\IA-Project-Unsupervised-ML
Existe el CSV: True

In [5]:
print(f"Número de filas: {mushrooms.shape[0]}")
print(f"Número de columnas: {mushrooms.shape[1]}")

Número de filas: 8124
Número de columnas: 23

In [6]:
mushrooms.info()

<class 'pandas.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   str
 1   cap-shape                 8124 non-null   str
 2   cap-surface               8124 non-null   str
 3   cap-color                 8124 non-null   str
 4   bruises                   8124 non-null   str
 5   odor                      8124 non-null   str
 6   gill-attachment           8124 non-null   str
 7   gill-spacing              8124 non-null   str
 8   gill-size                 8124 non-null   str
 9   gill-color                8124 non-null   str
 10  stalk-shape               8124 non-null   str
 11  stalk-root                8124 non-null   str
 12  stalk-surface-above-ring  8124 non-null   str
 13  stalk-surface-below-ring  8124 non-null   str
 14  stalk-color-above-ring    8124 non-null   str
 15  stalk-color-below-ring    8124 non-null   str
 16  veil-type                 8124 non-null   str
 17  veil-color                8124 non-null   str
 18  ring-number               8124 non-null   str
 19  ring-type                 8124 non-null   str
 20  spore-print-color         8124 non-null   str
 21  population                8124 non-null   str
 22  habitat                   8124 non-null   str
dtypes: str(23)
memory usage: 1.4 MB

In [7]:
mushrooms.isna().sum().sort_values(ascending=False)

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [8]:
unknown_counts = (mushrooms == "?").sum().sort_values(ascending=False)

unknown_counts[unknown_counts > 0]

stalk-root    2480
dtype: int64

In [9]:
stalk_root_unknown_percentage = (
    unknown_counts["stalk-root"] / len(mushrooms) * 100
)

print(
    f"Porcentaje desconocido en stalk-root: "
    f"{stalk_root_unknown_percentage:.2f}%"
)

Porcentaje desconocido en stalk-root: 30.53%

#### Valores ausentes encubiertos

La comprobación con `isna()` no detectó valores nulos convencionales. Sin embargo, al buscar el símbolo `?`, encontramos **2.480 valores desconocidos** en la variable `stalk-root`.

Estos valores representan aproximadamente el **30,53 % del dataset**, por lo que no pueden considerarse un problema menor.

Eliminar directamente todas estas filas supondría perder casi un tercio de las observaciones. Más adelante compararemos alternativas como la eliminación, la imputación o el tratamiento de `?` como una categoría independiente antes de tomar una decisión.

In [11]:
n_values = (
    mushrooms.nunique(dropna=False)
    .sort_values()
    .rename_axis("feature")
    .reset_index(name="n_values")
)

constant_features = n_values[n_values["n_values"] == 1]

constant_features

     feature  n_values
0  veil-type         1

In [12]:
mushrooms["veil-type"].value_counts(dropna=False)

veil-type
p    8124
Name: count, dtype: int64

#### Columna constante

La variable `veil-type` contiene un único valor (`p`) en las **8.124 observaciones**.

Al no presentar variabilidad, esta columna no permite diferenciar unas setas de otras y no aportará información a los algoritmos de clustering.

Por este motivo, será candidata a eliminarse durante la etapa de limpieza. Todavía no la eliminamos porque en esta etapa solo estamos identificando y documentando problemas del dataset.

In [13]:
class_distribution = (
    mushrooms["class"]
    .value_counts()
    .rename_axis("class")
    .reset_index(name="count")
)

class_distribution["percentage"] = (
    class_distribution["count"] / len(mushrooms) * 100
).round(2)

class_distribution

  class  count  percentage
0     e   4208        51.8
1     p   3916        48.2

#### Distribución de la etiqueta de referencia

La variable `class` está formada por:

- **4.208 setas comestibles (`e`)**, que representan el **51,8 %** del dataset.
- **3.916 setas venenosas (`p`)**, que representan el **48,2 %** del dataset.

La distribución está prácticamente equilibrada, por lo que ninguna clase domina claramente sobre la otra.

Esta etiqueta no se utilizará para crear los clusters. Se reservará para evaluar posteriormente si los grupos encontrados mediante aprendizaje no supervisado se parecen a las clases reales.

In [14]:
category_summary = pd.DataFrame({
    "feature": mushrooms.columns,
    "n_values": [
        mushrooms[column].nunique(dropna=False)
        for column in mushrooms.columns
    ],
    "values": [
        sorted(mushrooms[column].astype(str).unique())
        for column in mushrooms.columns
    ],
})

category_summary

                     feature  n_values                                values
0                      class         2                                [e, p]
1                  cap-shape         6                    [b, c, f, k, s, x]
2                cap-surface         4                          [f, g, s, y]
3                  cap-color        10        [b, c, e, g, n, p, r, u, w, y]
4                    bruises         2                                [f, t]
5                       odor         9           [a, c, f, l, m, n, p, s, y]
6            gill-attachment         2                                [a, f]
7               gill-spacing         2                                [c, w]
8                  gill-size         2                                [b, n]
9                 gill-color        12  [b, e, g, h, k, n, o, p, r, u, w, y]
10               stalk-shape         2                                [e, t]
11                stalk-root         5                       [?, b, c, e, r]
12  stalk-surface-above-ring         4                          [f, k, s, y]
13  stalk-surface-below-ring         4                          [f, k, s, y]
14    stalk-color-above-ring         9           [b, c, e, g, n, o, p, w, y]
15    stalk-color-below-ring         9           [b, c, e, g, n, o, p, w, y]
16                 veil-type         1                                   [p]
17                veil-color         4                          [n, o, w, y]
18               ring-number         3                             [n, o, t]
19                 ring-type         5                       [e, f, l, n, p]
20         spore-print-color         9           [b, h, k, n, o, r, u, w, y]
21                population         6                    [a, c, n, s, v, y]
22                   habitat         7                 [d, g, l, m, p, u, w]

#### Revisión de las categorías

Las 23 variables del dataset son categóricas y presentan cardinalidades comprendidas entre 1 y 12 valores diferentes.

Los principales hallazgos son:

- `veil-type` contiene una sola categoría (`p`), por lo que es una variable constante.
- `stalk-root` contiene la categoría `?`, utilizada para representar valores desconocidos.
- No se observan otros símbolos evidentes de valores ausentes en las demás columnas.
- `gill-color` es la variable con mayor cardinalidad, con 12 categorías.

Las letras utilizadas en el dataset representan categorías nominales. No son valores numéricos ni establecen un orden. Por ejemplo, no podemos afirmar que una categoría `b` sea mayor o menor que una categoría `n`.

Esta característica será importante durante el preprocesado, ya que los algoritmos necesitarán una representación numérica que no introduzca un orden artificial entre las categorías.

In [15]:
frequency_tables = []

for column in mushrooms.columns:
    frequency = (
        mushrooms[column]
        .value_counts(dropna=False)
        .rename_axis("category")
        .reset_index(name="count")
    )

    frequency["percentage"] = (
        frequency["count"] / len(mushrooms) * 100
    ).round(2)

    frequency.insert(0, "feature", column)
    frequency_tables.append(frequency)

category_frequencies = pd.concat(
    frequency_tables,
    ignore_index=True
)

category_frequencies.sort_values("percentage").head(15)

                     feature category  count  percentage
7                  cap-shape        c      4        0.05
11               cap-surface        g      4        0.05
88                veil-color        y      8        0.10
74    stalk-color-above-ring        y      8        0.10
20                 cap-color        u     16        0.20
21                 cap-color        r     16        0.20
50                gill-color        r     24        0.30
61  stalk-surface-above-ring        y     24        0.30
83    stalk-color-below-ring        y     24        0.30
6                  cap-shape        s     32        0.39
73    stalk-color-above-ring        c     36        0.44
82    stalk-color-below-ring        c     36        0.44
91               ring-number        n     36        0.44
96                 ring-type        n     36        0.44
32                      odor        m     36        0.44